### ISSUE TITLE
Ledger Exercise Timeouts with TestRunner

### ISSUE THREAD

**Issue by martinfreedman** [exercism/fsharp#1043]
Ledger Exercise Timeouts with TestRunner but works fine with local testing.

This does not look like a combinatoric optimization issue nor does any test look like it is long running.

Checked with my student exercism@polfo and re-checked with my existing long submitted solution.

**Comment by ErikSchierboom** [comment]
Could you post the code that was used?

**Comment by martinfreedman** [comment]
Try any. Try yours. Should have posted this in FSharp/TestRunner. Anyway here is my student's:

```﻿module Ledger

open System
open System.Globalization

type Entry = { Date: DateTime; Description: string; Change: int }

let mkEntry date description change =
    { Date = DateTime.Parse(date, CultureInfo.InvariantCulture); Description = description; Change = change }
        
let formatLedger currency locale entries =
    let formatHeader =
        match locale with
        | "nl-NL" -> sprintf "%-10s | %-25s | %-13s" "Datum" "Omschrijving" "Verandering"
        | "en-US" -> sprintf "%-10s | %-25s | %-13s" "Date" "Description" "Change"
        | _ -> failwith "not valid culture"

    let formatLine = sprintf "%-10s | %-25s | %13s"

    let formatDate (entry: Entry) =
        match locale with
        | "nl-NL" -> entry.Date.ToString "dd-MM-yyyy"
        | "en-US" -> entry.Date.ToString "MM\/dd\/yyyy"
        | _ -> failwith "not valid culture"

    let formatDesc (entry: Entry) =
        if entry.Description.Length > 25 then entry.Description.[0..21] + "..." 
        else entry.Description
        
    let symbol = 
        match currency with
        | "EUR" -> "€"
        | "USD" -> "$"
        | _ -> failwith "not valid currency"

    let formatChange (entry: Entry) =
        let cultureFormat =
            match locale with
            | "en-US" -> sprintf "%s#,#0.00 ;(%s#,#0.00)" symbol symbol
            | "nl-NL" -> sprintf "%s #,#0.00 ;%s -#,#0.00" symbol symbol
            | _ -> failwith "not valid culture"
        (float entry.Change / 100.0).ToString(cultureFormat, CultureInfo(locale))

    let formatEntry (entry: Entry) =
        "\n" + formatLine (formatDate entry) (formatDesc entry) (formatChange entry)

    let result = entries |> List.sortBy (fun x -> x.Date, x.Description, x.Change) |> List.map (formatEntry) |> String.Concat

    formatHeader + result
```

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/fsharp/pull/1045 should fix this. With that change, everything works locally on my machine.

**Comment by martinfreedman** [comment]
Nope still does not work. Check running my old solution though the online editor, still times out.

**Comment by martinfreedman** [comment]
Unless there is a daily push to prod and it has not happened yet

**Comment by ErikSchierboom** [comment]
@martinfreedman Did you upgrade your exercise?

**Comment by martinfreedman** [comment]
@

> @martinfreedman Did you upgrade your exercise?

No I just re-ran my year old solution, needed to add a space to let the test run and it still timeouts. (Says nothing about it being out of date)

**Comment by martinfreedman** [comment]
Even did the `System.Environment.NewLine` change (from `'\n'`) which _did_ work for my student solution but _not_ for mine!

**Comment by ErikSchierboom** [comment]
You don't see this on your exercise page:

<img width="1412" alt="Screenshot 2021-11-20 at 10 19 56" src="https://user-images.githubusercontent.com/135246/142721168-211e30c1-f935-4896-9c8e-b663c12c19cc.png">

**Comment by ErikSchierboom** [comment]
After updating, I can run the tests:
<img width="461" alt="Screenshot 2021-11-20 at 10 21 27" src="https://user-images.githubusercontent.com/135246/142721198-8cd53a1a-ccb5-48f3-be7f-c3351f4014c5.png">

**Comment by martinfreedman** [comment]
Saw it now. Look for it previously and this was not there. Updated exercise re-ran tests and it passed!
